apiVersion: v1
kind: Service
metadata:
    name: "k8lab-afbf"
    labels:
        app: "k8lab-afbf"
spec:
    type: LoadBalancer
    ports:
    - port: 5433
      targetPort: 5433
      protocol: TCP
      name: http
    selector:
        app: "k8lab-afbf"