on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: k8lab20.azurecr.io
        username: ${{ secrets.acr_k8lab20_username }}
        password: ${{ secrets.acr_k8lab20_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Lab-k8-Azure" -f  "K8-Lab" -t k8lab20.azurecr.io/k8lab:${{ github.sha }}
        docker push k8lab20.azurecr.io/k8lab:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8lab_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8lab41c7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8lab41c7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8lab41c7
        container-registry-url: k8lab20.azurecr.io
        container-registry-username: ${{ secrets.acr_k8lab20_username }}
        container-registry-password: ${{ secrets.acr_k8lab20_password }}
        secret-name: k8labdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: k8lab41c7
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          k8lab20.azurecr.io/k8lab:${{ github.sha }}
        imagepullsecrets: |
          k8labdockerauth